htmlURL = ['https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=brain-computer%20interface%20%7C%20BCI',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=fnirs',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=TDCS%20%7C%20TACS%20%7C%20TRNS',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=braille',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=tactile%20acuity',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=low%20vision',
       'https://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Search&db=PubMed&term=Oostenveld%2C%20Robert%5BAuthor%5D',
       'http://iopscience.iop.org/journal/rss/1741-2552', 'https://www.frontiersin.org/journals/neuroscience',
       'https://www.frontiersin.org/journals/neurorobotics', 'https://www.frontiersin.org/journals/human-neuroscience',
       'https://www.frontiersin.org/journals/computational-neuroscience',
       'https://www.frontiersin.org/journals/neuroinformatics', 'http://www.pnas.org', 'http://www.jneurosci.org',
       'http://www.jneurosci.org', 'http://www.nature.com/neuro/current_issue/',
       'http://www.nature.com/subjects/neuroscience', 'http://biorxiv.org', 'http://arxiv.org/', 'http://arxiv.org/',
       'https://www.embs.org', 'http://ieeexplore.ieee.org', 'http://ieeexplore.ieee.org', 'http://ieeexplore.ieee.org',
       'http://ieeexplore.ieee.org', 'http://ieeexplore.ieee.org', 'https://brain.ieee.org',
       'https://lifesciences.ieee.org', 'http://www.nejm.org', 'https://www.sciencedirect.com/journal/neuroimage',
       'https://www.sciencedirect.com/journal/journal-of-neuroscience-methods',
       'https://www.sciencedirect.com/journal/neuroscience', 'http://www.sciencedirect.com',
       'https://www.journals.elsevier.com/clinical-neurophysiology/rss', 'https://erpinfo.org/blog/',
       'https://sapienlabs.co', 'http://daniellakens.blogspot.com/',
       'https://www.fens.org/News-Activities/Awards/Awards-Directory/Awards-Directory/',
       'https://www.fens.org/News-Activities/News/']


xmlURLs = [
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1rSUu--tbw4049Wgf_RdKXdtNCvGW0lVBZFpHe7zaN4k4DwoD5',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1JKSd2KF3MGnV7oFVD2g6PNu7rHRFDsLyCNjKkkf4KHBUA3c8P',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=143rKCPgMwbasrj66gQ1r1ebioUg42SIGRyVKSoW4m6X-ecQ00',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=165yO28ehHLjXJb8W3JvTx2bYozdDe8IvyFRBlOfHZxFR8o1uX',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1no_pWrlHWS46ep2l9cVOQkZ1QsEMPlx7YY7aF6AfCIqP-RYZd',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1xePBFBNvSIegfqCbvp45N3V9WgCNCS63Z1PLmhwJSPGd18QMT',
    'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/erss.cgi?rss_guid=1BUB2BG5RbxOblm-hBbiJWEhGG43qlVrvGNHOTqBKva9wWrItM',
    'http://iopscience.iop.org/journal/rss/1741-2552', 'https://www.frontiersin.org/journals/neuroscience/rss',
    'https://www.frontiersin.org/journals/neurorobotics/rss',
    'https://www.frontiersin.org/journals/human-neuroscience/rss',
    'https://www.frontiersin.org/journals/computational-neuroscience/rss',
    'https://www.frontiersin.org/journals/neuroinformatics/rss',
    'http://feeds.feedburner.com/ProceedingsOfTheNationalAcademyOfSciencesNeuroscience',
    'http://www.jneurosci.org/rss/current.xml', 'http://www.jneurosci.org/rss/This_Week_in_The_Journal.xml',
    'http://feeds.nature.com/neuro/rss/current', 'https://www.nature.com/subjects/neuroscience.rss',
    'http://connect.biorxiv.org/biorxiv_xml.php?subject=neuroscience', 'http://export.arxiv.org/rss/q-bio.NC',
    'http://export.arxiv.org/rss/cs.HC', 'https://www.embs.org/feed/', 'https://ieeexplore.ieee.org/rss/TOC6720218.XML',
    'https://ieeexplore.ieee.org/rss/TOC4664312.XML', 'https://ieeexplore.ieee.org/rss/TOC10.XML',
    'https://ieeexplore.ieee.org/rss/TOC8335903.XML', 'https://ieeexplore.ieee.org/rss/TOC4543165.XML',
    'https://brain.ieee.org/feed/', 'https://lifesciences.ieee.org/feed/',
    'https://search.nejm.org/search?cnt=20&start_month=12&start_year=2008&w=*&restrict=doctype%3Aarticle&srt=0&isort=date&ts=rss&af=topic:1',
    'https://rss.sciencedirect.com/publication/science/10538119',
    'https://rss.sciencedirect.com/publication/science/01650270_OA/open-access',
    'https://rss.sciencedirect.com/publication/science/03064522',
    'http://rss.sciencedirect.com/publication/science/00068993',
    'https://www.journals.elsevier.com/clinical-neurophysiology/rss', 'https://erpinfo.org/blog?format=RSS',
    'https://sapienlabs.co/feed/', 'http://daniellakens.blogspot.com/feeds/posts/default?alt=rss',
    'https://www.fens.org/RSS/Awards/', 'https://www.fens.org/RSS/News/']
